# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ta.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import icon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(292, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon(':/watermelon.ico')
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 271, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(80, 50, 181, 31))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.account = QtWidgets.QLineEdit(self.frame)
        self.account.setGeometry(QtCore.QRect(80, 10, 181, 31))
        self.account.setText("")
        self.account.setObjectName("account")
        self.account_type = QtWidgets.QComboBox(self.frame)
        self.account_type.setGeometry(QtCore.QRect(80, 90, 111, 31))
        self.account_type.setObjectName("account_type")
        self.account_type.addItem("")
        self.account_type.addItem("")
        self.account_type.addItem("")
        self.account_type.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.loginbutton = QtWidgets.QPushButton(self.frame)
        self.loginbutton.setGeometry(QtCore.QRect(200, 90, 61, 31))
        self.loginbutton.setIconSize(QtCore.QSize(16, 10))
        self.loginbutton.setObjectName("loginbutton")
        self.projectGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.projectGroup.setGeometry(QtCore.QRect(10, 150, 271, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectGroup.sizePolicy().hasHeightForWidth())
        self.projectGroup.setSizePolicy(sizePolicy)
        self.projectGroup.setTitle("")
        self.projectGroup.setObjectName("projectGroup")
        self.label_4 = QtWidgets.QLabel(self.projectGroup)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.projectname = QtWidgets.QComboBox(self.projectGroup)
        self.projectname.setGeometry(QtCore.QRect(10, 50, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectname.sizePolicy().hasHeightForWidth())
        self.projectname.setSizePolicy(sizePolicy)
        self.projectname.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.projectname.setObjectName("projectname")
        self.label_5 = QtWidgets.QLabel(self.projectGroup)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.totalhours = QtWidgets.QLineEdit(self.projectGroup)
        self.totalhours.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.totalhours.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.totalhours.setObjectName("totalhours")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.projectGroup)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 180, 251, 181))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_6 = QtWidgets.QLabel(self.projectGroup)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.projectGroup)
        self.label_7.setGeometry(QtCore.QRect(10, 370, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.generate = QtWidgets.QPushButton(self.projectGroup)
        self.generate.setGeometry(QtCore.QRect(10, 470, 251, 41))
        self.generate.setObjectName("generate")
        self.label_8 = QtWidgets.QLabel(self.projectGroup)
        self.label_8.setGeometry(QtCore.QRect(10, 520, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.output_number = QtWidgets.QLabel(self.projectGroup)
        self.output_number.setGeometry(QtCore.QRect(70, 520, 191, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.output_number.setFont(font)
        self.output_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_number.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output_number.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.output_number.setObjectName("output_number")
        self.date = QtWidgets.QLabel(self.projectGroup)
        self.date.setGeometry(QtCore.QRect(90, 150, 161, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setUnderline(False)
        self.date.setFont(font)
        self.date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date.setText("")
        self.date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date.setObjectName("date")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.projectGroup)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 410, 251, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CCU時數申報小幫手"))
        self.label.setText(_translate("MainWindow", "帳號:"))
        self.label_2.setText(_translate("MainWindow", "密碼:"))
        self.account_type.setItemText(0, _translate("MainWindow", "計畫主持人"))
        self.account_type.setItemText(1, _translate("MainWindow", "專任助理"))
        self.account_type.setItemText(2, _translate("MainWindow", "兼任助理"))
        self.account_type.setItemText(3, _translate("MainWindow", "臨時工"))
        self.label_3.setText(_translate("MainWindow", "身份:"))
        self.loginbutton.setText(_translate("MainWindow", "登入"))
        self.label_4.setText(_translate("MainWindow", "計畫名稱:"))
        self.label_5.setText(_translate("MainWindow", "一個月總時長:"))
        self.label_6.setText(_translate("MainWindow", "開始日期:"))
        self.label_7.setText(_translate("MainWindow", "工作內容:"))
        self.generate.setText(_translate("MainWindow", "產生批號"))
        self.label_8.setText(_translate("MainWindow", "批號:"))
        self.output_number.setText(_translate("MainWindow", "<none>"))
